### ISSUE TITLE
Class syntax

### ISSUE THREAD

**Issue by rchrd2** [softek/puppet-java7#6]
Does this work with the newer class based syntax? 
I'd imagine it would be something like:

```
class { 'java7': }
```

If it already does, it would be great to see this in the documentation.

Thank you.

**Comment by antonlindstrom** [comment]
Yes, that should work fine.

`include java7` and `class { 'java7': }` should basically be the same thing.

**Comment by rchrd2** [comment]
Oh great. It could be helpful to add that to the readme for beginners. Thank you.

**Comment by smerchek** [comment]
Yes, if you only specify them once, then `include java7` and `class { 'java7: }` are equivalent.

See the [Puppet documentation: Defining Classes](http://docs.puppetlabs.com/puppet/latest/reference/lang_classes.html#declaring-classes) for more information.

You may need to be careful because defining `class { 'java7': }` multiple times will give you errors.
